
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmfagudcscfkrupdkoxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtZmFndWRjc2Nma3J1cGRrb3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MzQ2NDIsImV4cCI6MjA2MjIxMDY0Mn0.gxxI248ACvdbbtRke8B0jWiL9xyhR8Ajt04phWq_IeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
